{% set name = "utm" %}
{% set version = "0.8.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/utm-{{ version }}.tar.gz
  sha256: 634d5b6221570ddc6a1e94afa5c51bae92bcead811ddc5c9bc0a20b847c2dafa

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - utm
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Turbo87/utm
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Bidirectional UTM-WGS84 converter for python.
  description: Bidirectional UTM-WGS84 converter for python.
  doc_url: https://github.com/Turbo87/utm
  dev_url: https://github.com/Turbo87/utm

extra:
  recipe-maintainers:
    - snowman2
    - Turbo87
